Lua 没有语法上的异常处理，而是通过函数抛出和捕获异常
- `function error(v|{err})`：抛出异常
- `function pcall(f)`：调用一个函数，若无异常，返回 true+函数返回值；否则，返回 false+err

> [!note] error() 的 level 参数和 xpcall() 暂不考虑
> 

在 LuaState 中添加 `Error` 和 `PCall` 方法

| 函数    | 说明                                          |
| ----- | ------------------------------------------- |
| Error | 将栈顶的值作为异常抛出，返回 Error 错误代码（便于 Go 函数使用）       |
| PCall | 若无异常，与 Call 一致；返回 LUA_OK；否则，捕获错误并留在栈顶，返回错误码 |
## Error

直接通过 `panic` 抛出异常即可

```go title:state/api_misc.go
func (self *luaState) Error() int {
	err := self.stack.pop()
	panic(err)
}
```
## PCall

使用 `defer` 捕获异常，将异常推入栈顶。注意弹出调用栈

```go title:state/api_call.go hl:5-13
func (self *luaState) PCall(nArgs, nResults, msgh int) (status int) {
	caller := self.stack
	status = api.LUA_ERRERR

	defer func() {
		// 异常捕获，将捕获的异常存入栈顶
		if err := recover(); err != nil {
			for self.stack != caller {
				self.popLuaStack()
			}
			self.stack.push(err)
		}
	}()

	self.Call(nArgs, nResults)
	status = api.LUA_OK
	return
}
```

创建 `error`，`pCall` 函数，注入